# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: daidai/protocol/sim/sim_observation_service.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'daidai/protocol/sim/sim_observation_service.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from daidai.protocol.common import pose_pb2 as daidai_dot_protocol_dot_common_dot_pose__pb2
try:
  daidai_dot_protocol_dot_common_dot_position__pb2 = daidai_dot_protocol_dot_common_dot_pose__pb2.daidai_dot_protocol_dot_common_dot_position__pb2
except AttributeError:
  daidai_dot_protocol_dot_common_dot_position__pb2 = daidai_dot_protocol_dot_common_dot_pose__pb2.daidai.protocol.common.position_pb2
try:
  daidai_dot_protocol_dot_common_dot_quaternion__pb2 = daidai_dot_protocol_dot_common_dot_pose__pb2.daidai_dot_protocol_dot_common_dot_quaternion__pb2
except AttributeError:
  daidai_dot_protocol_dot_common_dot_quaternion__pb2 = daidai_dot_protocol_dot_common_dot_pose__pb2.daidai.protocol.common.quaternion_pb2
from daidai.protocol.common import joint_pb2 as daidai_dot_protocol_dot_common_dot_joint__pb2

from daidai.protocol.common.pose_pb2 import *
from daidai.protocol.common.joint_pb2 import *

DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n1daidai/protocol/sim/sim_observation_service.proto\x12\x0f\x64\x61idai.protocol\x1a!daidai/protocol/common/pose.proto\x1a\"daidai/protocol/common/joint.proto\"h\n\x0cInitSceneReq\x12\x15\n\rcamera_config\x18\x01 \x01(\t\x12\x16\n\x0escene_usd_path\x18\x02 \x01(\t\x12)\n\nrobot_pose\x18\x03 \x01(\x0b\x32\x15.daidai.protocol.Pose\"\x1b\n\x0cInitSceneRsp\x12\x0b\n\x03msg\x18\x01 \x01(\t2b\n\x15SimObservationService\x12I\n\tInitScene\x12\x1d.daidai.protocol.InitSceneReq\x1a\x1d.daidai.protocol.InitSceneRspP\x00P\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'daidai.protocol.sim.sim_observation_service_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_INITSCENEREQ']._serialized_start=141
  _globals['_INITSCENEREQ']._serialized_end=245
  _globals['_INITSCENERSP']._serialized_start=247
  _globals['_INITSCENERSP']._serialized_end=274
  _globals['_SIMOBSERVATIONSERVICE']._serialized_start=276
  _globals['_SIMOBSERVATIONSERVICE']._serialized_end=374
# @@protoc_insertion_point(module_scope)
