# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: daidai/protocol/common/pose.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'daidai/protocol/common/pose.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from daidai.protocol.common import position_pb2 as daidai_dot_protocol_dot_common_dot_position__pb2
from daidai.protocol.common import quaternion_pb2 as daidai_dot_protocol_dot_common_dot_quaternion__pb2

from daidai.protocol.common.position_pb2 import *
from daidai.protocol.common.quaternion_pb2 import *

DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n!daidai/protocol/common/pose.proto\x12\x0f\x64\x61idai.protocol\x1a%daidai/protocol/common/position.proto\x1a\'daidai/protocol/common/quaternion.proto\"e\n\x04Pose\x12+\n\x08position\x18\x01 \x01(\x0b\x32\x19.daidai.protocol.Position\x12\x30\n\x0borientation\x18\x02 \x01(\x0b\x32\x1b.daidai.protocol.QuaternionP\x00P\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'daidai.protocol.common.pose_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_POSE']._serialized_start=134
  _globals['_POSE']._serialized_end=235
# @@protoc_insertion_point(module_scope)
