# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from daidai.protocol.sim import sim_observation_service_pb2 as daidai_dot_protocol_dot_sim_dot_sim__observation__service__pb2

GRPC_GENERATED_VERSION = '1.76.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in daidai/protocol/sim/sim_observation_service_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class SimObservationServiceStub(object):
    """*
    @brief 预定义仿真服务支持的功能 
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.InitScene = channel.unary_unary(
                '/daidai.protocol.SimObservationService/InitScene',
                request_serializer=daidai_dot_protocol_dot_sim_dot_sim__observation__service__pb2.InitSceneReq.SerializeToString,
                response_deserializer=daidai_dot_protocol_dot_sim_dot_sim__observation__service__pb2.InitSceneRsp.FromString,
                _registered_method=True)


class SimObservationServiceServicer(object):
    """*
    @brief 预定义仿真服务支持的功能 
    """

    def InitScene(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_SimObservationServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'InitScene': grpc.unary_unary_rpc_method_handler(
                    servicer.InitScene,
                    request_deserializer=daidai_dot_protocol_dot_sim_dot_sim__observation__service__pb2.InitSceneReq.FromString,
                    response_serializer=daidai_dot_protocol_dot_sim_dot_sim__observation__service__pb2.InitSceneRsp.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'daidai.protocol.SimObservationService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('daidai.protocol.SimObservationService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class SimObservationService(object):
    """*
    @brief 预定义仿真服务支持的功能 
    """

    @staticmethod
    def InitScene(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/daidai.protocol.SimObservationService/InitScene',
            daidai_dot_protocol_dot_sim_dot_sim__observation__service__pb2.InitSceneReq.SerializeToString,
            daidai_dot_protocol_dot_sim_dot_sim__observation__service__pb2.InitSceneRsp.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
